### ISSUE TITLE
Issue with the React-Router-v4-with-redux code

### ISSUE THREAD

**Issue by VishuM-WDev** [haideralishah/React-Router-v4-with-redux#1]

**Comment by VishuM-WDev** [comment]
import React, { Component } from 'react';
import Routers from './Route';
import Provider from 'react-redux';
import store from '.store';

class App extends Component {
  render() {
    return (
      <Provider store={store}>
      <Routers />
      </Provider>
    );
  }
}

export default App;

**Comment by haideralishah** [comment]
Make sure you have installed react-redux library.
